In [1]:
import pandas as pd

In [2]:
df_empty = pd.DataFrame()

In [3]:
type(df_empty)

pandas.core.frame.DataFrame

In [5]:
df_empty.shape

(0, 0)

In [7]:
df_empty.size

0

In [8]:
df_empty.ndim

2

In [9]:
df_empty.index

RangeIndex(start=0, stop=0, step=1)

In [10]:
df_empty.columns

RangeIndex(start=0, stop=0, step=1)

In [11]:
df_empty.values

array([], shape=(0, 0), dtype=float64)

In [12]:
data = {
    'Name': ['Alice', 'Bob', 'Chandni', 'Dawood'],
    'Age': [25, 30, 18, 22],
    'City': ['Mumbai', 'Kolkata', 'Delhi', 'Bengaluru']
}
df1 = pd.DataFrame(data)

In [13]:
df1.shape

(4, 3)

In [14]:
df1

      Name  Age       City
0    Alice   25     Mumbai
1      Bob   30    Kolkata
2  Chandni   18      Delhi
3   Dawood   22  Bengaluru

In [15]:
df1.ndim

2

In [16]:
df1.values

array([['Alice', 25, 'Mumbai'],
       ['Bob', 30, 'Kolkata'],
       ['Chandni', 18, 'Delhi'],
       ['Dawood', 22, 'Bengaluru']], dtype=object)

In [17]:
df1.dtypes

Name    object
Age      int64
City    object
dtype: object

In [18]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [38]:
indian_startup = pd.read_csv('indian_startups.csv', index_col='Company')

In [39]:
indian_startup.index

Index(['Urban Company', 'Classplus', 'Paytm', 'Apna', 'Razorpay', 'UpGrad',
       'Delhivery', '1mg', 'BigBasket', 'GoMechanic',
       ...
       'GirnarSoft', 'Meesho', 'Lenskart', 'Udaan', 'Zolve', 'SafexPay',
       'Pariksha', 'Fyllo', 'CredFlow', 'HalaPlay Technologies'],
      dtype='object', name='Company', length=300)

In [40]:
indian_startup = pd.read_csv('indian_startups.csv', nrows=6)

In [41]:
indian_startup

,Company,City,Starting Year,Founders,Industries,Description,No. of Employees,Funding Amount in $,Funding Round,No. of Investors
0,Urban Company,Gurgaon,2014,"Abhiraj Singh Bhal, Raghav Chandra, Varun Khaitan","Apps, Home Services, Marketplace, Service Indu...",Urban is a marketplace for independent contrac...,1001-5000,445920356,12,16
1,Classplus,Noida,2018,"Bhaswat Agarwal, Bikash Dash, Mukul Rustagi, N...","B2B, E-Learning, EdTech, Education, Mobile App...",Classplus is a mobile-first SaaS platform that...,101-250,89506451,10,20
2,Paytm,Noida,2010,"Akshay Khanna, Vijay Shekhar Sharma","E-Commerce, Finance, Financial Services, Inter...",Paytm is a payment gateway that allows users a...,501-1000,32448851,4,4
3,Apna,Mumbai,2019,Nirmit Parikh,"Employment, Human Resources, Recruiting, Staff...",Apna is a professional networking and job-sear...,101-250,93450000,4,6
4,Razorpay,Bengaluru,2014,"Harshil Mathur, Shashank Kumar","Financial Services, FinTech, Payments, Software","Razorpay is a payment acceptance, processing, ...",1001-5000,366600000,7,29
5,UpGrad,Mumbai,2015,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","E-Learning, EdTech, Education",UpGrad is a higher education portal that offer...,1001-5000,176283446,4,4

In [34]:
indian_startup

,Company,City,Starting Year,Founders,Industries,Description,No. of Employees,Funding Amount in $,Funding Round,No. of Investors
0,Urban Company,Gurgaon,2014,"Abhiraj Singh Bhal, Raghav Chandra, Varun Khaitan","Apps, Home Services, Marketplace, Service Indu...",Urban is a marketplace for independent contrac...,1001-5000,445920356,12,16
1,Classplus,Noida,2018,"Bhaswat Agarwal, Bikash Dash, Mukul Rustagi, N...","B2B, E-Learning, EdTech, Education, Mobile App...",Classplus is a mobile-first SaaS platform that...,101-250,89506451,10,20
2,Paytm,Noida,2010,"Akshay Khanna, Vijay Shekhar Sharma","E-Commerce, Finance, Financial Services, Inter...",Paytm is a payment gateway that allows users a...,501-1000,32448851,4,4
3,Apna,Mumbai,2019,Nirmit Parikh,"Employment, Human Resources, Recruiting, Staff...",Apna is a professional networking and job-sear...,101-250,93450000,4,6
4,Razorpay,Bengaluru,2014,"Harshil Mathur, Shashank Kumar","Financial Services, FinTech, Payments, Software","Razorpay is a payment acceptance, processing, ...",1001-5000,366600000,7,29
...,...,...,...,...,...,...,...,...,...,...
295,SafexPay,Thane,2017,Ravi Gupta,"FinTech, Payments",Safexpay is a B2B2B finance company that speci...,51-100,5280000,1,2
296,Pariksha,Pune,2015,"Deepak Choudhary, Karanvir Singh Shekhawat, Ut...","E-Learning, EdTech, Education, Skill Assessment",Pariksha - The Success App is India's leading ...,51-100,6065079,7,20
297,Fyllo,Bengaluru,2019,"Sachin Gautam, Sudhanshu Rai, Sumit Sheoran","Agriculture, AgTech, Artificial Intelligence, ...",Fyllo is a precision agriculture service provi...,Nov-50,557033,4,6
298,CredFlow,New Delhi,2019,Kunal Aggarwal,"Credit, Financial Services",CredFlow offers financial services that help y...,10-Jan,1824000,1,4
299,HalaPlay Technologies,Bengaluru,2016,Swapnil Saurav,"Digital Entertainment, Fantasy Sports, Sports",HalaPlay Technologies is a platform for daily ...,10-Jan,7964767,3,8

In [28]:
indian_startup.shape

(300, 10)

In [29]:
indian_startup.index

RangeIndex(start=0, stop=300, step=1)

In [30]:
indian_startup.ndim

2

In [31]:
indian_startup.size

3000

In [ ]:
indian_startup.