In [7]:
import pandas as pd
import numpy as np

In [8]:
data1 = {
    'Name': ['Ashok', 'Bob', 'Chandni', 'Dawood', 'Esha'],
    'Age': [25, 30, 18, 22, 30],
    'City': ['Mumbai', 'Kolkata', 'Delhi', 'Bengaluru', 'Agra'],
    'Inc June': [3000, 4000, 5000, 6000, np.nan],
    'Inc July': [3000, 4000, 5000, np.nan, 7000]
}
d1 = pd.DataFrame(data1)

In [9]:
d1

      Name  Age       City  Inc June  Inc July
0    Ashok   25     Mumbai    3000.0    3000.0
1      Bob   30    Kolkata    4000.0    4000.0
2  Chandni   18      Delhi    5000.0    5000.0
3   Dawood   22  Bengaluru    6000.0       NaN
4     Esha   30       Agra       NaN    7000.0

In [10]:
d1['Inc of June and July'] = d1['Inc June'] + d1['Inc July']

In [11]:
d1

      Name  Age       City  Inc June  Inc July  Inc of June and July
0    Ashok   25     Mumbai    3000.0    3000.0                6000.0
1      Bob   30    Kolkata    4000.0    4000.0                8000.0
2  Chandni   18      Delhi    5000.0    5000.0               10000.0
3   Dawood   22  Bengaluru    6000.0       NaN                   NaN
4     Esha   30       Agra       NaN    7000.0                   NaN

In [14]:
d1['Inc of June and July'] = d1['Inc June'].add(d1['Inc July'], fill_value = 0) # .add() is a series method which works here

In [15]:
d1

      Name  Age       City  Inc June  Inc July  Inc of June and July
0    Ashok   25     Mumbai    3000.0    3000.0                6000.0
1      Bob   30    Kolkata    4000.0    4000.0                8000.0
2  Chandni   18      Delhi    5000.0    5000.0               10000.0
3   Dawood   22  Bengaluru    6000.0       NaN                6000.0
4     Esha   30       Agra       NaN    7000.0                7000.0

In [18]:
d1['Tax on Income'] = 0.01 * d1['Inc of June and July']

In [19]:
d1

,Name,Age,City,Inc June,Inc July,Inc of June and July,Tax on Income
0,Ashok,25,Mumbai,3000.0,3000.0,6000.0,60.0
1,Bob,30,Kolkata,4000.0,4000.0,8000.0,80.0
2,Chandni,18,Delhi,5000.0,5000.0,10000.0,100.0
3,Dawood,22,Bengaluru,6000.0,NaN,6000.0,60.0
4,Esha,30,Agra,NaN,7000.0,7000.0,70.0

In [20]:
d1[['Inc June', 'Inc July']] = d1[['Inc June', 'Inc July']].fillna(4)

In [21]:
d1

,Name,Age,City,Inc June,Inc July,Inc of June and July,Tax on Income
0,Ashok,25,Mumbai,3000.0,3000.0,6000.0,60.0
1,Bob,30,Kolkata,4000.0,4000.0,8000.0,80.0
2,Chandni,18,Delhi,5000.0,5000.0,10000.0,100.0
3,Dawood,22,Bengaluru,6000.0,4.0,6000.0,60.0
4,Esha,30,Agra,4.0,7000.0,7000.0,70.0

In [22]:
d1.loc[d1['City'].isin(['Mumbai', 'Delhi']), 'Tax on Income'] +=500

In [23]:
d1

,Name,Age,City,Inc June,Inc July,Inc of June and July,Tax on Income
0,Ashok,25,Mumbai,3000.0,3000.0,6000.0,560.0
1,Bob,30,Kolkata,4000.0,4000.0,8000.0,80.0
2,Chandni,18,Delhi,5000.0,5000.0,10000.0,600.0
3,Dawood,22,Bengaluru,6000.0,4.0,6000.0,60.0
4,Esha,30,Agra,4.0,7000.0,7000.0,70.0

In [24]:
d1.query('Age >=25')

,Name,Age,City,Inc June,Inc July,Inc of June and July,Tax on Income
0,Ashok,25,Mumbai,3000.0,3000.0,6000.0,560.0
1,Bob,30,Kolkata,4000.0,4000.0,8000.0,80.0
4,Esha,30,Agra,4.0,7000.0,7000.0,70.0