In [1]:
import pandas as pd

In [2]:
data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance', 'Finance', 'Finance'],
    'Product': ['ChatBot', 'Autoflagger', 'ChatBot', 'Autoflagger', 'ChatBot', 'Autoflagger', 'Autoflagger'],
    'Employee': ['Ashok', 'Bob', 'Chandni', 'Dawood', 'Esha', 'Falak', 'Girish'],
    'Salary': [50000, 55000, 60000, 65000, 70000, 72000, 80000],
    'Bonus': [5000, 6000, 7000, 8000, 9000, 9500, 10000]
}
df= pd.DataFrame(data)

In [3]:
df

  Department      Product Employee  Salary  Bonus
0         HR      ChatBot    Ashok   50000   5000
1         HR  Autoflagger      Bob   55000   6000
2         IT      ChatBot  Chandni   60000   7000
3         IT  Autoflagger   Dawood   65000   8000
4    Finance      ChatBot     Esha   70000   9000
5    Finance  Autoflagger    Falak   72000   9500
6    Finance  Autoflagger   Girish   80000  10000

In [4]:
df.dtypes

Department    object
Product       object
Employee      object
Salary         int64
Bonus          int64
dtype: object

In [5]:
department_sum = df.groupby('Department').sum()

In [6]:
department_sum

                                  Product         Employee  Salary  Bonus
Department
Finance     ChatBotAutoflaggerAutoflagger  EshaFalakGirish  222000  28500
HR                     ChatBotAutoflagger         AshokBob  105000  11000
IT                     ChatBotAutoflagger    ChandniDawood  125000  15000

In [7]:
department_c = df.groupby('Department').count()

In [8]:
department_c

            Product  Employee  Salary  Bonus
Department
Finance           3         3       3      3
HR                2         2       2      2
IT                2         2       2      2

In [9]:
department_mean = df.groupby('Department')['Salary'].mean()

In [10]:
department_mean

Department
Finance    74000.0
HR         52500.0
IT         62500.0
Name: Salary, dtype: float64

In [11]:
department_mean = df.groupby('Department')[['Salary', 'Bonus']].mean()

In [12]:
department_mean

             Salary   Bonus
Department
Finance     74000.0  9500.0
HR          52500.0  5500.0
IT          62500.0  7500.0

In [13]:
product_department_sum = df.groupby(['Product', 'Department']).sum()

In [14]:
product_department_sum

                           Employee  Salary  Bonus
Product     Department
Autoflagger Finance     FalakGirish  152000  19500
            HR                  Bob   55000   6000
            IT               Dawood   65000   8000
ChatBot     Finance            Esha   70000   9000
            HR                Ashok   50000   5000
            IT              Chandni   60000   7000

In [15]:
department_sum.index

Index(['Finance', 'HR', 'IT'], dtype='object', name='Department')

In [16]:
product_department_sum.index

MultiIndex([('Autoflagger', 'Finance'),
            ('Autoflagger',      'HR'),
            ('Autoflagger',      'IT'),
            (    'ChatBot', 'Finance'),
            (    'ChatBot',      'HR'),
            (    'ChatBot',      'IT')],
           names=['Product', 'Department'])

The `.pivot()` method can be used to reshape the DataFrame

In [17]:
df_pivoted = df.pivot(index='Department', columns='Employee', values='Salary')

In [18]:
df_pivoted

Employee      Ashok      Bob  Chandni   Dawood     Esha    Falak   Girish
Department
Finance         NaN      NaN      NaN      NaN  70000.0  72000.0  80000.0
HR          50000.0  55000.0      NaN      NaN      NaN      NaN      NaN
IT              NaN      NaN  60000.0  65000.0      NaN      NaN      NaN

In [19]:
df_pivoted2 = df.pivot(index=['Product','Department'], columns='Employee', values=['Salary', 'Bonus'])

In [20]:
df_pivoted2

                         Salary                                               \
Employee                  Ashok      Bob  Chandni   Dawood     Esha    Falak
Product     Department
Autoflagger Finance         NaN      NaN      NaN      NaN      NaN  72000.0
            HR              NaN  55000.0      NaN      NaN      NaN      NaN
            IT              NaN      NaN      NaN  65000.0      NaN      NaN
ChatBot     Finance         NaN      NaN      NaN      NaN  70000.0      NaN
            HR          50000.0      NaN      NaN      NaN      NaN      NaN
            IT              NaN      NaN  60000.0      NaN      NaN      NaN

                                  Bonus                                  \
Employee                 Girish   Ashok     Bob Chandni  Dawood    Esha
Product     Department
Autoflagger Finance     80000.0     NaN     NaN     NaN     NaN     NaN
            HR              NaN     NaN  6000.0     NaN     NaN     NaN
            IT              NaN     NaN     NaN     NaN  8000.0     NaN
ChatBot     Finance         NaN     NaN     NaN     NaN     NaN  9000.0
            HR              NaN  5000.0     NaN     NaN     NaN     NaN
            IT              NaN     NaN     NaN  7000.0     NaN     NaN


Employee                 Falak   Girish
Product     Department
Autoflagger Finance     9500.0  10000.0
            HR             NaN      NaN
            IT             NaN      NaN
ChatBot     Finance        NaN      NaN
            HR             NaN      NaN
            IT             NaN      NaN

In [21]:
df_pivoted_table = df.pivot_table(index='Department', values='Employee', aggfunc='count')

In [22]:
df_pivoted_table

            Employee
Department
Finance            3
HR                 2
IT                 2