In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('cars_dataset.csv')

In [5]:
df.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000
mean,96.530612,0.931973,98.087755,172.873469,65.710884,53.664626,2527.469388,126.523810,3.303469,3.266599,10.255238,102.734694,5157.823129,25.537415,31.047619,13248.402497
std,60.034386,1.225639,6.108257,12.835948,2.185448,2.564879,555.939552,46.137575,0.272921,0.282661,4.051558,39.467227,476.132417,6.928472,7.326377,8694.473053
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.680000,2.360000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,44.500000,0.000000,94.500000,165.300000,63.900000,51.600000,2045.000000,97.000000,3.050000,3.135000,8.600000,69.000000,4800.000000,19.500000,25.000000,7429.000000
50%,94.000000,1.000000,96.500000,171.700000,65.400000,53.700000,2380.000000,110.000000,3.270000,3.270000,9.000000,95.000000,5200.000000,25.000000,30.000000,9895.000000
75%,146.500000,2.000000,100.400000,180.200000,66.500000,55.650000,2911.000000,143.000000,3.580000,3.400000,9.400000,116.000000,5500.000000,31.000000,37.000000,16207.500000
max,204.000000,3.000000,120.900000,208.100000,72.000000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000

We can index and slice DataFrames by position with iloc[], the integer-location-based (position-based) indexer

In [6]:
df.iloc[0]

car_ID                               1
symboling                            3
carname             alfa-romero giulia
doornumber                         two
carbody                    convertible
enginelocation                   front
wheelbase                         88.6
carlength                        168.8
carwidth                          64.1
carheight                         48.8
curbweight                        2548
cylindernumber                    four
enginesize                         130
boreratio                         3.47
stroke                            2.68
compressionratio                   9.0
horsepower                         111
peakrpm                           5000
citympg                             21
highwaympg                          27
price                          13495.0
Name: 0, dtype: object

In [7]:
df.iloc[::2]

,car_ID,symboling,carname,doornumber,carbody,enginelocation,wheelbase,carlength,carwidth,carheight,...,cylindernumber,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,two,convertible,front,88.6,168.8,64.1,48.8,...,four,130,3.47,2.68,9.0,111,5000,21,27,13495.000
2,3,1,alfa-romero Quadrifoglio,two,hatchback,front,94.5,171.2,65.5,52.4,...,six,152,2.68,3.47,9.0,154,5000,19,26,16500.000
4,5,2,audi 100ls,four,sedan,front,99.4,176.6,66.4,54.3,...,five,136,3.19,3.40,8.0,115,5500,18,22,17450.000
6,8,1,audi 5000,four,wagon,front,105.8,192.7,71.4,55.7,...,five,136,3.19,3.40,8.5,110,5500,19,25,18920.000
8,10,0,audi 5000s (diesel),two,hatchback,front,99.5,178.2,67.9,52.0,...,five,131,3.13,3.40,7.0,160,5500,16,22,17859.167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,192,0,volkswagen rabbit,four,sedan,front,100.4,180.2,66.9,55.1,...,five,136,3.19,3.40,8.5,110,5500,19,24,13295.000
140,195,-2,volvo 145e (sw),four,sedan,front,104.3,188.8,67.2,56.2,...,four,141,3.78,3.15,9.5,114,5400,23,28,12940.000
142,197,-2,volvo 244dl,four,sedan,front,104.3,188.8,67.2,56.2,...,four,141,3.78,3.15,9.5,114,5400,24,28,15985.000
144,199,-2,volvo 264gl,four,sedan,front,104.3,188.8,67.2,56.2,...,four,130,3.62,3.15,7.5,162,5100,17,22,18420.000
146,204,-1,volvo 246,four,sedan,front,109.1,188.8,68.9,55.5,...,six,145,3.01,3.40,23.0,106,4800,26,27,22470.000

In [9]:
df.iloc[0, :]

car_ID                               1
symboling                            3
carname             alfa-romero giulia
doornumber                         two
carbody                    convertible
enginelocation                   front
wheelbase                         88.6
carlength                        168.8
carwidth                          64.1
carheight                         48.8
curbweight                        2548
cylindernumber                    four
enginesize                         130
boreratio                         3.47
stroke                            2.68
compressionratio                   9.0
horsepower                         111
peakrpm                           5000
citympg                             21
highwaympg                          27
price                          13495.0
Name: 0, dtype: object

In [10]:
df.iloc[:2, :5]

   car_ID  symboling              carname doornumber      carbody
0       1          3   alfa-romero giulia        two  convertible
1       2          3  alfa-romero stelvio        two  convertible

In [11]:
type(df.iloc[:2, :5]) # a selection of multiple rows and columns is 2D and thereforew a Pandas DataFrame

pandas.core.frame.DataFrame

In [13]:
df.iloc[::-1, ::-1] # rows and columns in reverse

,price,highwaympg,citympg,peakrpm,horsepower,compressionratio,stroke,boreratio,enginesize,cylindernumber,...,carheight,carwidth,carlength,wheelbase,enginelocation,carbody,doornumber,carname,symboling,car_ID
146,22470.0,27,26,4800,106,23.0,3.40,3.01,145,six,...,55.5,68.9,188.8,109.1,front,sedan,four,volvo 246,-1,204
145,18950.0,22,17,5100,162,7.5,3.15,3.62,130,four,...,57.5,67.2,188.8,104.3,front,wagon,four,volvo diesel,-1,200
144,18420.0,22,17,5100,162,7.5,3.15,3.62,130,four,...,56.2,67.2,188.8,104.3,front,sedan,four,volvo 264gl,-2,199
143,16515.0,28,24,5400,114,9.5,3.15,3.78,141,four,...,57.5,67.2,188.8,104.3,front,wagon,four,volvo 245,-1,198
142,15985.0,28,24,5400,114,9.5,3.15,3.78,141,four,...,56.2,67.2,188.8,104.3,front,sedan,four,volvo 244dl,-2,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,17450.0,22,18,5500,115,8.0,3.40,3.19,136,five,...,54.3,66.4,176.6,99.4,front,sedan,four,audi 100ls,2,5
3,13950.0,30,24,5500,102,10.0,3.40,3.19,109,four,...,54.3,66.2,176.6,99.8,front,sedan,four,audi 100 ls,2,4
2,16500.0,26,19,5000,154,9.0,3.47,2.68,152,six,...,52.4,65.5,171.2,94.5,front,hatchback,two,alfa-romero Quadrifoglio,1,3
1,16500.0,27,21,5000,111,9.0,2.68,3.47,130,four,...,48.8,64.1,168.8,88.6,front,convertible,two,alfa-romero stelvio,3,2
0,13495.0,27,21,5000,111,9.0,2.68,3.47,130,four,...,48.8,64.1,168.8,88.6,front,convertible,two,alfa-romero giulia,3,1

In [18]:
df

,car_ID,symboling,carname,doornumber,carbody,enginelocation,wheelbase,carlength,carwidth,carheight,...,cylindernumber,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,two,convertible,front,88.6,168.8,64.1,48.8,...,four,130,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,two,convertible,front,88.6,168.8,64.1,48.8,...,four,130,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,two,hatchback,front,94.5,171.2,65.5,52.4,...,six,152,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,four,sedan,front,99.8,176.6,66.2,54.3,...,four,109,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,four,sedan,front,99.4,176.6,66.4,54.3,...,five,136,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,197,-2,volvo 244dl,four,sedan,front,104.3,188.8,67.2,56.2,...,four,141,3.78,3.15,9.5,114,5400,24,28,15985.0
143,198,-1,volvo 245,four,wagon,front,104.3,188.8,67.2,57.5,...,four,141,3.78,3.15,9.5,114,5400,24,28,16515.0
144,199,-2,volvo 264gl,four,sedan,front,104.3,188.8,67.2,56.2,...,four,130,3.62,3.15,7.5,162,5100,17,22,18420.0
145,200,-1,volvo diesel,four,wagon,front,104.3,188.8,67.2,57.5,...,four,130,3.62,3.15,7.5,162,5100,17,22,18950.0
146,204,-1,volvo 246,four,sedan,front,109.1,188.8,68.9,55.5,...,six,145,3.01,3.40,23.0,106,4800,26,27,22470.0

In [28]:
df.loc[54, 'symboling'] # here, the label of the row is the same as its numeric index (0)

np.int64(-1)

In [29]:
df.loc[:, 'symboling': 'wheelbase']

,symboling,carname,doornumber,carbody,enginelocation,wheelbase
0,3,alfa-romero giulia,two,convertible,front,88.6
1,3,alfa-romero stelvio,two,convertible,front,88.6
2,1,alfa-romero Quadrifoglio,two,hatchback,front,94.5
3,2,audi 100 ls,four,sedan,front,99.8
4,2,audi 100ls,four,sedan,front,99.4
...,...,...,...,...,...,...
142,-2,volvo 244dl,four,sedan,front,104.3
143,-1,volvo 245,four,wagon,front,104.3
144,-2,volvo 264gl,four,sedan,front,104.3
145,-1,volvo diesel,four,wagon,front,104.3
146,-1,volvo 246,four,sedan,front,109.1

In [34]:
df.loc[df['carbody']=='sedan',:]

,car_ID,symboling,carname,doornumber,carbody,enginelocation,wheelbase,carlength,carwidth,carheight,...,cylindernumber,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
3,4,2,audi 100 ls,four,sedan,front,99.8,176.6,66.2,54.3,...,four,109,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,four,sedan,front,99.4,176.6,66.4,54.3,...,five,136,3.19,3.40,8.0,115,5500,18,22,17450.0
5,6,2,audi fox,two,sedan,front,99.8,177.3,66.3,53.1,...,five,136,3.19,3.40,8.5,110,5500,19,25,15250.0
7,9,1,audi 4000,four,sedan,front,105.8,192.7,71.4,55.9,...,five,131,3.13,3.40,8.3,140,5500,17,20,23875.0
9,11,2,bmw 320i,two,sedan,front,101.2,176.8,64.8,54.3,...,four,108,3.50,2.80,8.8,101,5800,23,29,16430.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,193,0,volkswagen rabbit custom,four,sedan,front,100.4,180.2,66.9,55.1,...,four,97,3.01,3.40,23.0,68,4500,33,38,13845.0
140,195,-2,volvo 145e (sw),four,sedan,front,104.3,188.8,67.2,56.2,...,four,141,3.78,3.15,9.5,114,5400,23,28,12940.0
142,197,-2,volvo 244dl,four,sedan,front,104.3,188.8,67.2,56.2,...,four,141,3.78,3.15,9.5,114,5400,24,28,15985.0
144,199,-2,volvo 264gl,four,sedan,front,104.3,188.8,67.2,56.2,...,four,130,3.62,3.15,7.5,162,5100,17,22,18420.0
146,204,-1,volvo 246,four,sedan,front,109.1,188.8,68.9,55.5,...,six,145,3.01,3.40,23.0,106,4800,26,27,22470.0

In [35]:
df.columns

Index(['car_ID', 'symboling', 'carname', 'doornumber', 'carbody',
       'enginelocation', 'wheelbase', 'carlength', 'carwidth', 'carheight',
       'curbweight', 'cylindernumber', 'enginesize', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [36]:
df.index

RangeIndex(start=0, stop=147, step=1)