In [1]:
import pandas as pd

In [7]:
df_volumes = pd.read_csv('GOOGL_volume.csv')
df_prices = pd.read_csv('GOOGL_prices.csv')

In [8]:
df_prices

       Date    Open    High     Low   Close
0  1/3/2006  211.47  218.05  209.32  217.83
1  1/4/2006  222.17  224.70  220.09  222.84
2  1/5/2006  223.22  226.00  220.97  225.85
3  1/6/2006  228.66  235.49  226.85  233.06
4  1/9/2006  233.44  236.94  230.70  233.68

In [6]:
df_volumes

        Date    Volume
0   1/3/2006  13137450
1   1/4/2006  15292353
2   1/5/2006  10815661
3   1/9/2006  12795837
4  1/10/2006   9104719

Merging the Data Frames

In [9]:
df_inner_join = pd.merge(df_volumes, df_prices, on = 'Date', how='inner')

In [10]:
df_inner_join

       Date    Volume    Open    High     Low   Close
0  1/3/2006  13137450  211.47  218.05  209.32  217.83
1  1/4/2006  15292353  222.17  224.70  220.09  222.84
2  1/5/2006  10815661  223.22  226.00  220.97  225.85
3  1/9/2006  12795837  233.44  236.94  230.70  233.68

In [11]:
df_cross_join = pd.merge(df_volumes, df_prices, how='cross')

In [12]:
df_cross_join

       Date_x    Volume    Date_y    Open    High     Low   Close
0    1/3/2006  13137450  1/3/2006  211.47  218.05  209.32  217.83
1    1/3/2006  13137450  1/4/2006  222.17  224.70  220.09  222.84
2    1/3/2006  13137450  1/5/2006  223.22  226.00  220.97  225.85
3    1/3/2006  13137450  1/6/2006  228.66  235.49  226.85  233.06
4    1/3/2006  13137450  1/9/2006  233.44  236.94  230.70  233.68
5    1/4/2006  15292353  1/3/2006  211.47  218.05  209.32  217.83
6    1/4/2006  15292353  1/4/2006  222.17  224.70  220.09  222.84
7    1/4/2006  15292353  1/5/2006  223.22  226.00  220.97  225.85
8    1/4/2006  15292353  1/6/2006  228.66  235.49  226.85  233.06
9    1/4/2006  15292353  1/9/2006  233.44  236.94  230.70  233.68
10   1/5/2006  10815661  1/3/2006  211.47  218.05  209.32  217.83
11   1/5/2006  10815661  1/4/2006  222.17  224.70  220.09  222.84
12   1/5/2006  10815661  1/5/2006  223.22  226.00  220.97  225.85
13   1/5/2006  10815661  1/6/2006  228.66  235.49  226.85  233.06
14   1/5/2006  10815661  1/9/2006  233.44  236.94  230.70  233.68
15   1/9/2006  12795837  1/3/2006  211.47  218.05  209.32  217.83
16   1/9/2006  12795837  1/4/2006  222.17  224.70  220.09  222.84
17   1/9/2006  12795837  1/5/2006  223.22  226.00  220.97  225.85
18   1/9/2006  12795837  1/6/2006  228.66  235.49  226.85  233.06
19   1/9/2006  12795837  1/9/2006  233.44  236.94  230.70  233.68
20  1/10/2006   9104719  1/3/2006  211.47  218.05  209.32  217.83
21  1/10/2006   9104719  1/4/2006  222.17  224.70  220.09  222.84
22  1/10/2006   9104719  1/5/2006  223.22  226.00  220.97  225.85
23  1/10/2006   9104719  1/6/2006  228.66  235.49  226.85  233.06
24  1/10/2006   9104719  1/9/2006  233.44  236.94  230.70  233.68